### Customer does not exist
     
POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{
  "customerId": 10,
  "type": "Camembert",
  "count": 2
}
### Wrong count

POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{
"customerId": 1,
"type": "Camembert",
"count": 0
}

### Valid create

POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{
  "customerId": 1,
  "type": "Camembert",
  "count": 2000
}

### Order does not exist

POST http://localhost:8080/order/cancel/10
Content-Type: application/json
Accept: application/json

### Valid cancel
#
#POST http://localhost:8080/order/cancel/863b769f-2eb0-4363-9c7b-b8941feb7572
#Content-Type: application/json
#Accept: application/json

